version: '3.1'

services:
  reverse-proxy:
    image: traefik:1.7 # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - '8080:8080' # The Traefik Web UI (enabled by --api)
      - '8081:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
